// constants for reducers
export const actionTypes = {
    FETCH_BAG_OBJECTS: 'FETCH_BAG_OBJECTS',
    FETCH_BAG_OBJECTS_SUCCESS: 'FETCH_BAG_OBJECTS_SUCCESS',
    FETCH_BAG_OBJECTS_FAIL: 'FETCH_BAG_OBJECTS_FAIL',

    FETCH_BAG_UPDATE: 'FETCH_BAG_UPDATE',
    FETCH_BAG_UPDATE_SUCCESS: 'FETCH_BAG_UPDATE_SUCCESS',
    FETCH_BAG_UPDATE_FAIL: 'FETCH_BAG_UPDATE_FAIL',

    FETCH_SCANNER_OBJECTS: 'FETCH_SCANNER_OBJECTS',
    FETCH_SCANNER_OBJECTS_SUCCESS: 'FETCH_SCANNER_OBJECTS_SUCCESS',
    FETCH_SCANNER_OBJECTS_FAIL: 'FETCH_SCANNER_OBJECTS_FAIL',

    UPDATE_SCANNER_OBJECT: 'UPDATE_SCANNER_OBJECT',
    UPDATE_SCANNER_OBJECT_SUCCESS: 'UPDATE_SCANNER_OBJECT_SUCCESS',
    UPDATE_SCANNER_OBJECT_FAIL: 'UPDATE_SCANNER_OBJECT_FAIL',

    FETCH_USER_OBJECT: 'FETCH_USER_OBJECT',
    FETCH_USER_OBJECT_SUCCESS: 'FETCH_USER_OBJECT_SUCCESS',
    FETCH_USER_OBJECT_FAIL: 'FETCH_USER_OBJECT FAIL',
}